language: node_js
node_js:
  - '17'
install:
  - npm install
script:
  - npm run lint
  - npm run spell:check
  - npm run snyk-protect
  - npm run snyk-test
  - npm run test
  - npm run coveralls
before_deploy:
  - npm run build
  - cd dist
  - cp ../{.npmignore,package.json,LICENSE,README.md} .
deploy:
  edge: true
  provider: npm
  email: '$email'
  api_key: '$npm_token'
  cleanup: false
  on:
    tags: true
    repo: ymchun/ics
